export enum TRANGTHAI {
    DRAFT = "Bản nháp",
    CHOPHEDUYET = "Chờ duyệt",
    TRALAI = "Trả lại",
    CHOPHANXE = "Chờ phân xe",
    CHOCAPVE = "Chờ cấp vé",
    CHOPBDONGTRINH = "Chờ phòng ban đồng trình phê duyệt",
    DANGKY = "Đăng ký",
    CHOTHANHTOAN = "Chờ thanh toán",
    CHOTAODUTHAO = 'CHOTAODUTHAO',
    CHOCHUYENDO = 'CHOCHUYENDO',
    CHOBANHANHQD = 'CHOBANHANHQD',

    LUONG_CHOCHUYEN_DUTHAO_DO = 'LUONG_CHOCHUYEN_DUTHAO_DO',
	LUONG_CHO_BANHANH_VB_DO = 'LUONG_CHO_BANHANH_VB_DO',
	LUONG_TRALAI = 'LUONG_TRALAI',
	LUONG_KETTHUC = 'LUONG_KETTHUC'
}
