export enum TRANGTHAI_FILEBAOCAO {
    CHUACHUYENKY = "CHUA_CHUYENKY",
    DACHUYENKY = "DA_CHUYENKY",
    CVTCNSDAKY = "CV_TCNS_DAKY",
    LDTCNSDAKY = "LD_TCNS_DAKY",
    LDTCNSTRALAI = "LD_TCNS_TRALAI",
    LDDVTRALAI = "LD_DV_TRALAI",
    DONVIDAKY = "LD_DONVI_DAKY",
    DONVICAPTRENTRALAI = "DV_CAPTREN_TRALAI",
    DONVICAPTRENCHOTBAOCAO = "DV_CAPTREN_CHOT_BC",
}
