export enum TRANGTHAI_FILE_BAOCAO_KYSO_CODE {
    CHUA_CHUYENKY = "CHUA_CHUYENKY",
    DA_CHUYENKY = "DA_CHUYENKY",
    CV_TCNS_DAKY = "CV_TCNS_DAKY",
    LD_TCNS_DAKY = "LD_TCNS_DAKY",
    LD_TCNS_TRALAI = "LD_TCNS_TRALAI",
    LD_DV_TRALAI = "LD_DV_TRALAI",
    LD_DONVI_DAKY = "LD_DONVI_DAKY",
    DV_CAPTREN_TRALAI = "DV_CAPTREN_TRALAI",
    DV_CAPTREN_CHOT_BC = "DV_CAPTREN_CHOT_BC",
}